http:
  port: 8080

apiEndpoints:
  api:
    host: "*"

serviceEndpoints:
  app:
    urls:
      - "http://app1:3000/"
      - "http://app2:3000/"
      - "http://app3:3000/"
      - "http://app4:3000/"
      - "http://app5:3000/"

policies:
  - proxy

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: app
              strategy: round-robin
